### Pandas Practice 4
Merging And Joining

Learn to merge and join

In [1]:
import pandas as pd

# DataFrame 1 - Customer orders
orders = pd.DataFrame({
    'order_id': [1, 2, 3, 4, 5],
    'customer_id': [101, 102, 103, 101, 104],
    'amount': [250, 150, 300, 200, 175]
})

# DataFrame 2 - Customer details
customers = pd.DataFrame({
    'customer_id': [101, 102, 103, 105],
    'name': ['Alice', 'Bob', 'Charlie', 'David'],
    'city': ['Chennai', 'Mumbai', 'Delhi', 'Bangalore']
})

print(orders)
print(customers)

   order_id  customer_id  amount
0         1          101     250
1         2          102     150
2         3          103     300
3         4          101     200
4         5          104     175
   customer_id     name       city
0          101    Alice    Chennai
1          102      Bob     Mumbai
2          103  Charlie      Delhi
3          105    David  Bangalore

In [2]:
inner = pd.merge(orders, customers, on='customer_id', how='inner')
inner

   order_id  customer_id  amount     name     city
0         1          101     250    Alice  Chennai
1         2          102     150      Bob   Mumbai
2         3          103     300  Charlie    Delhi
3         4          101     200    Alice  Chennai

In [3]:
left = pd.merge(orders, customers, on='customer_id', how='left')
left

   order_id  customer_id  amount     name     city
0         1          101     250    Alice  Chennai
1         2          102     150      Bob   Mumbai
2         3          103     300  Charlie    Delhi
3         4          101     200    Alice  Chennai
4         5          104     175      NaN      NaN

In [5]:
right= pd.merge(orders, customers, on='customer_id', how='right')
right

   order_id  customer_id  amount     name       city
0       1.0          101   250.0    Alice    Chennai
1       4.0          101   200.0    Alice    Chennai
2       2.0          102   150.0      Bob     Mumbai
3       3.0          103   300.0  Charlie      Delhi
4       NaN          105     NaN    David  Bangalore

In [4]:
outer = pd.merge(orders,customers,on='customer_id',how='outer')
outer

   order_id  customer_id  amount     name       city
0       1.0          101   250.0    Alice    Chennai
1       4.0          101   200.0    Alice    Chennai
2       2.0          102   150.0      Bob     Mumbai
3       3.0          103   300.0  Charlie      Delhi
4       5.0          104   175.0      NaN        NaN
5       NaN          105     NaN    David  Bangalore