# Pandas Practice 4
## GroupBy and Aggregations
Learning to group data and perform aggregations - sum, mean, count, min, max on the movies dataset.

In [18]:
import pandas as pd 
df = pd.read_csv('movies_cleaned.csv')
df.shape

(45466, 25)

In [21]:
df.groupby('original_language')['vote_average'].mean().sort_values(ascending=False).head(10)

original_language
zu    8.300000
la    8.000000
mn    7.550000
am    7.450000
pa    7.350000
bn    7.137931
sq    7.080000
mk    7.060000
kn    6.966667
gl    6.900000
Name: vote_average, dtype: float64

Exercise 1 — Count of movies per language

In [ ]:
#df.groupby('original_language').size().sort_values(ascending=False).head(10) takes null value also
df.groupby('original_language')['title'].count().sort_values(ascending=False).head(10)

original_language
en    32267
fr     2438
it     1529
ja     1349
de     1080
es      994
ru      826
hi      508
ko      444
zh      409
Name: title, dtype: int64

Exercise 2 — Total revenue per language

In [27]:
pd.set_option('display.float_format', lambda x: f'{x:,.0f}')
df.groupby('original_language')['revenue'].sum().sort_values(ascending=False).head(10)

original_language
en   489,552,392,909
ja     3,689,455,852
zh     3,344,862,587
fr     2,688,029,702
hi     2,671,224,642
es     1,079,643,285
ko       968,643,475
cn       962,525,769
ru       813,809,870
de       762,197,134
Name: revenue, dtype: float64

In [29]:
pd.reset_option('display.float_format')
df.groupby('original_language')['vote_average'].agg(['mean', 'min', 'max', 'count']).sort_values('count', ascending=False).head(10)

                       mean  min   max  count
original_language
en                 5.491171  0.0  10.0  32267
fr                 6.056481  0.0  10.0   2438
it                 5.458797  0.0  10.0   1529
ja                 6.274203  0.0  10.0   1349
de                 5.863148  0.0  10.0   1080
es                 5.695171  0.0  10.0    994
ru                 5.701453  0.0  10.0    826
hi                 5.779134  0.0  10.0    508
ko                 6.570045  0.0   8.5    444
zh                 6.366993  0.0   9.0    409

In [30]:
df.groupby(['original_language', 'status'])['revenue'].sum().sort_values(ascending=False).head(10)

original_language  status
en                 Released    4.895026e+11
ja                 Released    3.689456e+09
zh                 Released    3.344863e+09
fr                 Released    2.688030e+09
hi                 Released    2.671225e+09
es                 Released    1.079643e+09
ko                 Released    9.686435e+08
cn                 Released    9.625258e+08
ru                 Released    7.959592e+08
de                 Released    7.621971e+08
Name: revenue, dtype: float64

In [33]:
pd.set_option('display.max_rows', 20)
df.groupby('original_language').agg(
    total_revenue = ('revenue', 'sum'),
    avg_voting=('vote_average', 'mean'),
    movie_count = ('title', 'count')
).sort_values('movie_count', ascending=False).head(10)

                   total_revenue  avg_voting  movie_count
original_language
en                  4.895524e+11    5.491171        32267
fr                  2.688030e+09    6.056481         2438
it                  6.920633e+08    5.458797         1529
ja                  3.689456e+09    6.274203         1349
de                  7.621971e+08    5.863148         1080
es                  1.079643e+09    5.695171          994
ru                  8.138099e+08    5.701453          826
hi                  2.671225e+09    5.779134          508
ko                  9.686435e+08    6.570045          444
zh                  3.344863e+09    6.366993          409

In [34]:
df.groupby('original_language').agg(
    total_revenue=('revenue', 'sum'),
    avg_voting=('vote_average', 'mean'),
    movie_count=('title', 'count')
).sort_values('movie_count', ascending=False).head(10).reset_index()

  original_language  total_revenue  avg_voting  movie_count
0                en   4.895524e+11    5.491171        32267
1                fr   2.688030e+09    6.056481         2438
2                it   6.920633e+08    5.458797         1529
3                ja   3.689456e+09    6.274203         1349
4                de   7.621971e+08    5.863148         1080
5                es   1.079643e+09    5.695171          994
6                ru   8.138099e+08    5.701453          826
7                hi   2.671225e+09    5.779134          508
8                ko   9.686435e+08    6.570045          444
9                zh   3.344863e+09    6.366993          409