# Pandas Practice 6
## Filtering, Querying and Cleaning Data
Boolean filtering, query(), handling duplicates, handling nulls, and string filtering on the movies dataset.

In [2]:
import pandas as pd
import numpy as nu

df = pd.read_csv('movies_cleaned.csv')
df.shape

(45466, 25)

### 1. Boolean Filtering
Filter rows based on conditions — similar to SQL WHERE clause

In [11]:
# Movies with vote_average > 8
high_rated = df[df['vote_average'] > 8]
high_rated[['title', 'vote_average', 'genres']].head(10)

,title,vote_average,genres
46,Se7en,8.1,Crime | Mystery | Thriller
49,The Usual Suspects,8.1,Drama | Crime | Thriller
109,Taxi Driver,8.1,Crime | Drama
186,Reckless,10.0,Fantasy | Comedy | Drama
256,Star Wars,8.1,Adventure | Action | Science Fiction
289,Leon: The Professional,8.2,Thriller | Crime | Drama
292,Pulp Fiction,8.3,Thriller | Crime
314,The Shawshank Redemption,8.5,Drama | Crime
351,Forrest Gump,8.2,Comedy | Drama | Romance
394,Girl in the Cadillac,10.0,Romance | Adventure | Crime | Drama

In [12]:
# Movies with vote_average > 8 AND revenue > 100 million
blockbusters = df[(df['vote_average'] > 8) & (df['revenue'] > 100000000)]
blockbusters[['title', 'vote_average', 'revenue']].head(10)

                                title  vote_average      revenue
46                              Se7en           8.1  327311859.0
256                         Star Wars           8.1  775398007.0
292                      Pulp Fiction           8.3  213928762.0
351                      Forrest Gump           8.2  677945399.0
522                  Schindler's List           8.3  321365567.0
586          The Silence of the Lambs           8.1  272742922.0
834                     The Godfather           8.5  245066411.0
1152  One Flew Over the Cuckoo's Nest           8.3  108981275.0
1154          The Empire Strikes Back           8.2  538400000.0
1201               Dead Poets Society           8.1  235860116.0

In [13]:
# Movies in English OR Hindi
en_hi = df[(df['original_language'] == 'en') | (df['original_language'] == 'hi')]
en_hi['original_language'].value_counts()

original_language
en    32269
hi      508
Name: count, dtype: int64

In [14]:
# Movies in English, Hindi or Tamil — cleaner than multiple OR conditions
selected = df[df['original_language'].isin(['en', 'hi', 'ta'])]
selected['original_language'].value_counts()

original_language
en    32269
hi      508
ta       78
Name: count, dtype: int64

In [15]:
# Movies NOT in English
non_english = df[~(df['original_language'] == 'en')]
non_english['original_language'].value_counts().head(10)

original_language
fr    2438
it    1529
ja    1350
de    1080
es     994
ru     826
hi     508
ko     444
zh     409
sv     384
Name: count, dtype: int64

### 2. Query Method
A cleaner, SQL-like way to filter — easier to read than boolean filtering

In [17]:
df.query('vote_average > 8')[['title', 'vote_average', 'genres']].head(10)

,title,vote_average,genres
46,Se7en,8.1,Crime | Mystery | Thriller
49,The Usual Suspects,8.1,Drama | Crime | Thriller
109,Taxi Driver,8.1,Crime | Drama
186,Reckless,10.0,Fantasy | Comedy | Drama
256,Star Wars,8.1,Adventure | Action | Science Fiction
289,Leon: The Professional,8.2,Thriller | Crime | Drama
292,Pulp Fiction,8.3,Thriller | Crime
314,The Shawshank Redemption,8.5,Drama | Crime
351,Forrest Gump,8.2,Comedy | Drama | Romance
394,Girl in the Cadillac,10.0,Romance | Adventure | Crime | Drama

In [18]:
# Multiple conditions
df.query('vote_average > 8 and revenue > 100000000')[['title', 'vote_average', 'revenue']].head(10)

                                title  vote_average      revenue
46                              Se7en           8.1  327311859.0
256                         Star Wars           8.1  775398007.0
292                      Pulp Fiction           8.3  213928762.0
351                      Forrest Gump           8.2  677945399.0
522                  Schindler's List           8.3  321365567.0
586          The Silence of the Lambs           8.1  272742922.0
834                     The Godfather           8.5  245066411.0
1152  One Flew Over the Cuckoo's Nest           8.3  108981275.0
1154          The Empire Strikes Back           8.2  538400000.0
1201               Dead Poets Society           8.1  235860116.0

In [19]:
# Using variables in query with @
min_rating = 7.5
min_revenue = 50000000
df.query('vote_average > @min_rating and revenue > @min_revenue')[['title', 'vote_average', 'revenue']].head(10)

                         title  vote_average      revenue
0                    Toy Story           7.7  373554033.0
5                         Heat           7.7  187436818.0
15                      Casino           7.8  116112375.0
46                       Se7en           8.1  327311859.0
108                 Braveheart           7.7  210000000.0
256                  Star Wars           8.1  775398007.0
292               Pulp Fiction           8.3  213928762.0
351               Forrest Gump           8.2  677945399.0
359              The Lion King           8.0  788241776.0
470  In the Name of the Father           7.6   65796862.0

### 3. String Filtering
Filter based on string content using .str accessor

In [20]:
# Movies with 'love' in title (case insensitive)
df[df['title'].str.contains('love', case=False, na=False)][['title', 'genres']].head(10)

                         title                     genres
39    Cry, the Beloved Country                      Drama
104            Nobody Loves Me    Drama | Comedy | Family
175       Love & Human Remains             Comedy | Drama
176                   Mad Love   Drama | Family | Romance
245           Immortal Beloved    Drama | Music | Romance
266                Love Affair            Drama | Romance
283         Nina Takes a Lover            Drama | Romance
291  A Pyromaniac's Love Story   Comedy | Drama | Romance
355             I Love Trouble  Action | Comedy | Romance
376   When a Man Loves a Woman            Drama | Romance

In [21]:
# Movies whose title starts with 'The'
df[df['title'].str.startswith('The', na=False)][['title']].head(10)

                         title
10      The American President
28   The City of Lost Children
49          The Usual Suspects
53               The Big Green
57                 The Postman
58            The Confessional
59  The Indian in the Cupboard
77          The Crossing Guard
78                   The Juror
79           The White Balloon

In [22]:
# Movies whose title is all uppercase
df[df['title'].str.isupper()][['title']].head(10)

         title
248       I.Q.
381     S.F.W.
1215         M
1430  B.A.P.S.
2392       8MM
3267       JFK
3433     U-571
3641       F/X
3642      F/X2
3682  H.O.T.S.

### 4. Handling Nulls
Identifying, filling and dropping null values

In [23]:
# Count nulls in each column
df.isnull().sum()

budget                          3
genres                       2442
homepage                    37684
id                              0
imdb_id                        17
original_language              11
original_title                  0
overview                      954
popularity                      6
poster_path                   386
production_companies        11881
production_countries         6288
release_date                   90
revenue                         6
runtime                       263
spoken_languages             3958
status                         87
tagline                     25054
title                           6
video                           6
vote_average                    6
vote_count                      6
collection_name             40975
collection_poster_path      41518
collection_backdrop_path    42203
dtype: int64

In [24]:
# Percentage of nulls per column
(df.isnull().sum() / len(df) * 100).round(2)

budget                       0.01
genres                       5.37
homepage                    82.88
id                           0.00
imdb_id                      0.04
original_language            0.02
original_title               0.00
overview                     2.10
popularity                   0.01
poster_path                  0.85
production_companies        26.13
production_countries        13.83
release_date                 0.20
revenue                      0.01
runtime                      0.58
spoken_languages             8.71
status                       0.19
tagline                     55.10
title                        0.01
video                        0.01
vote_average                 0.01
vote_count                   0.01
collection_name             90.12
collection_poster_path      91.32
collection_backdrop_path    92.82
dtype: float64

In [25]:
# Drop rows where title is null
df_clean = df.dropna(subset=['title'])
print(f"Before: {len(df)} rows")
print(f"After: {len(df_clean)} rows")

Before: 45466 rows
After: 45460 rows

In [26]:
# Fill null values
df_clean['overview'] = df_clean['overview'].fillna('No overview available')
df_clean['runtime'] = df_clean['runtime'].fillna(df_clean['runtime'].median())
df_clean[['title', 'overview', 'runtime']].head(10)

,title,overview,runtime
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",81.0
1,Jumanji,When siblings Judy and Peter discover an encha...,104.0
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,101.0
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",127.0
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,106.0
5,Heat,"Obsessive master thief, Neil McCauley leads a ...",170.0
6,Sabrina,An ugly duckling having undergone a remarkable...,127.0
7,Tom and Huck,"A mischievous young boy, Tom Sawyer, witnesses...",97.0
8,Sudden Death,International action superstar Jean Claude Van...,106.0
9,GoldenEye,James Bond must unmask the mysterious head of ...,130.0

### 5. Handling Duplicates

In [27]:
# Check for duplicates
print(f"Total rows: {len(df)}")
print(f"Duplicate rows: {df.duplicated().sum()}")

Total rows: 45466
Duplicate rows: 17

In [28]:
# Check duplicates based on specific column
print(f"Duplicate titles: {df.duplicated(subset=['title']).sum()}")

Duplicate titles: 3188

In [29]:
# Drop duplicates keeping first occurrence
df_dedup = df.drop_duplicates(subset=['title'], keep='first')
print(f"After dedup: {len(df_dedup)} rows")

After dedup: 42278 rows

### 6. Sorting

In [30]:
# Sort by single column
df.sort_values('vote_average', ascending=False)[['title', 'vote_average']].head(10)

                                                   title  vote_average
31082                                          Time Pass          10.0
45371              LEGO DC Super Hero Girls: Brain Drain          10.0
21798                                  Stealing a Nation          10.0
23851                                 Slaying the Badger          10.0
35999                                 The Lion of Thebes          10.0
28152                                     Goodbye & Amen          10.0
38463  ‘Rameau’s Nephew’ by Diderot (Thanx to Dennis ...          10.0
40954                                   Titus Andronicus          10.0
20209                                 Road to Redemption          10.0
32949                                    Pourquoi Israël          10.0

In [31]:
# Sort by multiple columns
df.sort_values(['vote_average', 'revenue'], ascending=[False, False])[['title', 'vote_average', 'revenue']].head(10)

,title,vote_average,revenue
1761,"Dancer, Texas Pop. 81",10.0,565592.0
186,Reckless,10.0,0.0
394,Girl in the Cadillac,10.0,0.0
706,"The Haunted World of Edward D. Wood, Jr.",10.0,0.0
738,Carmen Miranda: Bananas Is My Business,10.0,0.0
1634,Other Voices Other Rooms,10.0,0.0
2114,The Farmer's Wife,10.0,0.0
2653,Stiff Upper Lips,10.0,0.0
2948,Ten Benny,10.0,0.0
3160,Gendernauts: A Journey Through Shifting Identi...,10.0,0.0

In [32]:
df_clean.to_csv('movies_filtered_clean.csv', index=False)
print("Saved!")

Saved!

### Summary
- Boolean filtering with &, |, ~
- .query() for cleaner SQL-like filtering
- .str accessor for string operations
- Handling nulls with isnull(), fillna(), dropna()
- Handling duplicates with duplicated(), drop_duplicates()
- Sorting with sort_values()