# Pandas Practice 1
## Section 1 - Creating DataFrames from Dictionary and DateTime Operations
Creating a DataFrame from a Python dictionary and performing DateTime operations - extracting year, month, day, leap year, week of year and calculating age.

In [1]:
import pandas as pd

pd.__version__

'3.0.1'

In [2]:
df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'DOB' : ['1990-01-01', '1985-05-15', '1992-07-20', '1988-03-10', '1995-12-25'],
    'Score': [85, 90, 78, 92, 88]
})
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   DOB     5 non-null      str
 2   Score   5 non-null      int64
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [3]:
df.describe()

           Score
count   5.000000
mean   86.600000
std     5.458938
min    78.000000
25%    85.000000
50%    88.000000
75%    90.000000
max    92.000000

In [4]:
df.head(5)

      Name         DOB  Score
0    Alice  1990-01-01     85
1      Bob  1985-05-15     90
2  Charlie  1992-07-20     78
3    David  1988-03-10     92
4      Eve  1995-12-25     88

In [16]:
#df['year_of_birth']=df['DOB'].str[:4]

df['year_of_birth']=pd.to_datetime(df['DOB']).dt.year
df['month_of_birth']=pd.to_datetime(df['DOB']).dt.month
df['day_of_birth']=pd.to_datetime(df['DOB']).dt.day

df['is_leap_year']=pd.to_datetime(df['DOB']).dt.is_leap_year
df['day_of_week']=pd.to_datetime(df['DOB']).dt.day_name()

df.head(5)

,Name,DOB,Score,year_of_birth,month_of_birth,day_of_birth,is_leap_year,day_of_week,age
0,Alice,1990-01-01,85,1990,1,1,False,Monday,36
1,Bob,1985-05-15,90,1985,5,15,False,Wednesday,40
2,Charlie,1992-07-20,78,1992,7,20,True,Monday,33
3,David,1988-03-10,92,1988,3,10,True,Thursday,38
4,Eve,1995-12-25,88,1995,12,25,False,Monday,30

Finding Age using numpy

In [15]:
import numpy as np
today = pd.to_datetime('today')
year = today.year
date = today.day
month = today.month

birthday_date = pd.to_datetime(df['DOB']).dt.day
birthday_month = pd.to_datetime(df['DOB']).dt.month
birthday_year = pd.to_datetime(df['DOB']).dt.year

df['age'] = np.where(
    (month > birthday_month) | ((month == birthday_month) & (date >= birthday_date)),
    year - birthday_year,
    year - birthday_year - 1
)
df.head(5)

,Name,DOB,Score,year_of_birth,month_of_birth,day_of_birth,is_leap_year,day_of_week,age
0,Alice,1990-01-01,85,1990,1,1,False,Monday,36
1,Bob,1985-05-15,90,1985,5,15,False,Wednesday,40
2,Charlie,1992-07-20,78,1992,7,20,True,Monday,33
3,David,1988-03-10,92,1988,3,10,True,Thursday,38
4,Eve,1995-12-25,88,1995,12,25,False,Monday,30

Finding Age using apply with regular Python function

In [18]:
from datetime import date

def calculate_age(dob):
    today = date.today()
    dob = dob.date()
    age = today.year - dob.year
    if (today.month, today.day) < (dob.month, dob.day):
        age -= 1
    return age

df['age'] = pd.to_datetime(df['DOB']).apply(calculate_age)
df.head()

,Name,DOB,Score,year_of_birth,month_of_birth,day_of_birth,is_leap_year,day_of_week,age
0,Alice,1990-01-01,85,1990,1,1,False,Monday,36
1,Bob,1985-05-15,90,1985,5,15,False,Wednesday,40
2,Charlie,1992-07-20,78,1992,7,20,True,Monday,33
3,David,1988-03-10,92,1988,3,10,True,Thursday,38
4,Eve,1995-12-25,88,1995,12,25,False,Monday,30

Exercise 1 — Simple lambda on a column:
Add a new column that says "Pass" if Score >= 85, else "Fail":

In [22]:
df['result'] = df['Score'].apply(lambda x : 'Pass' if x>=85 else 'Fail')
df.head()

,Name,DOB,Score,year_of_birth,month_of_birth,day_of_birth,is_leap_year,day_of_week,age,result
0,Alice,1990-01-01,85,1990,1,1,False,Monday,36,Pass
1,Bob,1985-05-15,90,1985,5,15,False,Wednesday,40,Pass
2,Charlie,1992-07-20,78,1992,7,20,True,Monday,33,Fail
3,David,1988-03-10,92,1988,3,10,True,Thursday,38,Pass
4,Eve,1995-12-25,88,1995,12,25,False,Monday,30,Pass

Exercise 2 — Apply on multiple columns using axis=1:
Add a column that combines Name and age into a sentence:

In [27]:
df['student_details'] = df.apply(lambda x : f"{x['Name']} is {x['age']} years old", axis=1)

df.loc[:, 'student_details']

0      Alice is 36 years old
1        Bob is 40 years old
2    Charlie is 33 years old
3      David is 38 years old
4        Eve is 30 years old
Name: student_details, dtype: str

Exercise 3 — Apply with a named function:
Write a function that categorises age:

Below 35 → "Young"
35 to 40 → "Mid"
Above 40 → "Senior"

In [28]:
def student_category(age):
    if age <35:
        return 'Young'
    elif age <40 :
        return 'Middle-aged'
    else:
        return 'Senior'
    
df['age_category']=df['age'].apply(student_category)
df.loc[:, ['Name', 'age', 'age_category']]

      Name  age age_category
0    Alice   36  Middle-aged
1      Bob   40       Senior
2  Charlie   33        Young
3    David   38  Middle-aged
4      Eve   30        Young

#Lambda

Excercise 1 : String Operations

Add a column that converts Name to lower case

In [29]:
df['name_lower_case']=df['Name'].apply(lambda x : x.lower())
df.loc[:, ['Name', 'name_lower_case']]

      Name name_lower_case
0    Alice           alice
1      Bob             bob
2  Charlie         charlie
3    David           david
4      Eve             eve

Exercise 2 — Math operation:
Add a column that gives Score as a percentage out of 100 with a bonus of 5 marks:

In [33]:
df['percentage']=df['Score'].apply(lambda x : f"{min(x+5, 100)}%")
df.loc[:, ['Name', 'Score', 'percentage']]

      Name  Score percentage
0    Alice     85        90%
1      Bob     90        95%
2  Charlie     78        83%
3    David     92        97%
4      Eve     88        93%

Exercise 3 — Multiple columns with lambda:
Add a column that says "Birthday this month!" if born in March, else "Not this month":

In [32]:
df['birthday_alert'] = df.apply(lambda x : 'Birthday This Month!' if x['month_of_birth'] == month else '', axis=1   )
df.loc[:, ['Name', 'DOB', 'birthday_alert']]

      Name         DOB        birthday_alert
0    Alice  1990-01-01
1      Bob  1985-05-15
2  Charlie  1992-07-20
3    David  1988-03-10  Birthday This Month!
4      Eve  1995-12-25